### PR TITLE
Add ref, source and utm_source parameters as source attribute

### PR DESCRIPTION
**Pull request by BetaHuhn**
This PR adds support for ref, source and utm_source parameters introduced by [electerious/Ackee#173](https://github.com/electerious/Ackee/pull/173)

### CODE REVIEW

**Comment by BetaHuhn** [comment]
This implementation uses the [searchParams API](https://developer.mozilla.org/en-US/docs/Web/API/URL/searchParams) which is not supported by all browsers ([95%](https://caniuse.com/?search=searchParams)). Let me know if I should use another way of getting the URL parameters

**Comment by electerious** [comment]
> This implementation uses the searchParams API which is not supported by all browsers (95%). Let me know if I should use another way of getting the URL parameters

Please extract the parameters manually using `location.search`. `ackee-tracker` should be as backwards compatible as possible (I hope the rest of the script is compatible; I haven't tested in a while).

**Comment by BetaHuhn** [comment]
Okay, the parameters are now being extracted from location.search

**Comment by electerious** [comment]
Added this PR to the v5 branch. Now looking into the Ackee part.

**Pull request merged**
